"""Rebuild the two-page architecture PDF. PPT is edited separately, not regenerated here."""
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak
ROOT=Path(__file__).resolve().parents[1]
def build_pdf():
    styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='Copy',fontName='Helvetica',fontSize=10,leading=14,spaceAfter=9));styles.add(ParagraphStyle(name='Section',fontName='Helvetica-Bold',fontSize=13,leading=17,textColor=colors.HexColor('#4d3285'),spaceBefore=10,spaceAfter=7))
    story=[]
    def text(title,body):story.extend([Paragraph(title,styles['Section']),Paragraph(body,styles['Copy'])])
    story.append(Paragraph('LOGFLUX | Architecture',styles['Title']));story.append(Paragraph('SIH PS 26156 - NTRO | Verified prototype and experimental extensions',styles['Copy']))
    text('1. Core collection and preservation','Perimeter devices send TCP/TLS Syslog, best-effort UDP, authenticated HTTP or files. Bounded receivers commit original message bytes, SHA-256, source identity, receipt time, transport and framing to SQLite WAL before parsing. Raw records and normalized revisions are append-only. Recovery processes records left queued after a crash. Preservation begins at durable acceptance; transport acknowledgements are not application commit receipts.')
    text('2. Normalization and controlled adaptation','Trusted decoders extract attributes from supported structures and vendor subsets. Known mappings produce typed LOGFLUX events with quality issues, unmapped fields and provenance. Unknown or drifted fingerprints enter discovery. Drain3 and deterministic aliases assist structure/mapping review; optional local Qwen3 0.6B proposes mappings as untrusted data. Human semantic assertions and replay validation precede named approval.')
    text('3. WASM parser boundary','Approved field-selection modules are signed with Ed25519 and versioned. Wasmtime executes them with no host imports, 64 KiB memory, 10,000 fuel, a 64 KiB binary-input cap and a checked selector signature. Eleven adversarial tests exercise loops, memory limits, invalid modules and forbidden host access. Structural decoding remains trusted Python; bounded execution does not prove field meaning.')
    text('4. Evidence and operator workflow','Event manifests form domain-separated Merkle trees and ordered, signed checkpoints. Proof verification checks raw bytes, manifest, inclusion and a two-of-three pinned witness quorum. The UI provides seven workspaces for collection, review, evidence and investigation. Approved replay creates new revisions without replacing raw bytes. Timestamp-unit drift has an end-to-end constructed-fixture test and recording.')
    text('5. Exports and schema','JSONL, CSV and partial ECS projection support downstream use. The durable outbox retries generic HTTP or native Elasticsearch Bulk output. Stable event/revision IDs deduplicate Bulk retries; item errors remain pending. LOGFLUX is a custom OCSF-inspired schema, not full OCSF conformance. Detections are rules; the activity gauge is uncalibrated, not trained risk prediction.')
    story.append(PageBreak());story.append(Paragraph('Deployment and verification',styles['Title']))
    text('6. Network witness services','Optional authenticated services hold separate keys/databases and sign checkpoints in parallel. Remote binding requires TLS and distinct pinned public keys. Tests cover quorum availability, conflict rejection and restart/catch-up with three same-host processes. Single-witness verification is available offline and does not claim quorum. Independent custody requires separate machines and administrators; it is not established by this local trial.')
    text('7. Separate scale experiment','A four-partition Redpanda broker feeds one, two or four Python worker processes, which preserve raw Base64 bytes and normalized events in ClickHouse. Columnar writes complete before local offsets advance. Stable IDs enable logical deduplication. Workers seal batch Merkle trees; higher-level aggregation binds batch roots. All 2,000 raw hashes and shard proofs were verified in each local run, and committed-offset resume produced no new writes.')
    text('8. Measured scope','The broker gateway sustained 15,000 durably verified events/s for 60 seconds: 900,000/900,000 records, zero loss, 900 bounded Merkle batches and three witness signatures. The separate worker lab retains 1/2/4/16-worker comparisons, including the 7,018.75 events/s run, while the dashboard remains SQLite-based. Replicated production HA, multi-day capacity and billion-events/day operation are not claimed.')
    text('9. Packaging and acceptance','The non-root Docker image passed local health, authenticated ingestion, raw-byte retrieval, TCP/UDP receipt and evidence verification after restart. A GitHub Actions template is supplied; hosted execution awaits maintainer installation with workflow permission. Fonts and UI assets are local. Offline deployment requires staged wheels/images and optional local model runtime. Physical air-gap and model/firmware acceptance remain deployment-specific work.')
    text('10. Remaining enterprise work','Replicated storage, failover, automatic worker reassignment, WORM retention, independent custody, enterprise RBAC, full OCSF validation and broad device certification remain outside the verified prototype. Public corpus coverage includes unsupported sources and parse failures. Consult README Measured Results and the committed JSON reports for exact datasets, hashes, transport counts and timing boundaries.')
    path=ROOT/'docs/architecture.pdf';SimpleDocTemplate(str(path),pagesize=A4,rightMargin=40,leftMargin=40,topMargin=34,bottomMargin=34).build(story);return path
if __name__=='__main__':print(build_pdf())
